### ISSUE TITLE
pull request: added new Format option

### ISSUE THREAD

**Issue by DDdotDE** [rgomezjnr/GcodeFilenameFormatPlus#17]
Submiting a Issue because Githup doesn't want me to submit me to make a pull request

added a new formating option:
counter_down - giving each new file a lower number, based on  1000000 - (year*10000) - (month*1000) - (day*100) - (hour*10) - minute
this way, printers that sort the files based on the name should show the newest file at the top

[GcodeFilenameFormatPlus.py.txt](https://github.com/rgomezjnr/GcodeFilenameFormatPlus/files/12910379/GcodeFilenameFormatPlus.py.txt)

maybe this needs a rework to use the time at saving, not at importing the model

**Comment by rgomezjnr** [comment]
Hi what do you mean "Submiting a Issue because Githup doesn't want me to submit me to make a pull request"? Is there an error or warning when you attempt to create a PR? I haven't modified the repo PR settings so you should be able to create a PR.

**Comment by DDdotDE** [comment]
There was an Error while trying to send the PR, and it was faster / easier to submit a issue.
I can try again later to make a PR.
