### ISSUE TITLE
Model scale percentage

### ISSUE THREAD

**Issue by Dragonsbane** [rgomezjnr/GcodeFilenameFormatPlus#4]
Hi, first of all, awesome plug-in.
Just want to ask if it is possible to add the model scale percentage (individal for x,y,z and perhaps also a combined one) as parameters.

**Comment by rgomezjnr** [comment]
Hi I haven't found these parameters yet from searching the Cura and Ultimaker codebases, but I think they should be available to expose in GFF+, I'll keep looking and get back to you soon.

**Comment by qkdefus** [comment]
was about to make a request for this :)

**Comment by rgomezjnr** [comment]
Hey guys, sorry for the long wait, but I've figured how to get the scale option in the format. I still need to do some formatting of the scale values and figure out if or how to handle multiple objects with separate scale values.

![image](https://user-images.githubusercontent.com/55524335/144333896-91d3ed72-821c-483a-ae8f-9d7b0eb52b64.png)

![image](https://user-images.githubusercontent.com/55524335/144334215-306ddace-9d5f-4727-9a1f-35a4218f8d70.png)

**Comment by rgomezjnr** [comment]
GFF+ 0.2.0 has been released in the Cura Marketplace. Lmk if it works for you or if you have feedback.

Release notes

Added scale options:
[scale] - uniform scale of the object (%)
[scale_x] - scale of the object on the X axis (%)
[scale_y] - scale of the object on the Y axis (%)
[scale_z] - scale of the object on the Z axis (%)

**Comment by rgomezjnr** [comment]
@Dragonsbane @qkdefus Hey guys have you had a chance to test the scale options in GFF+ 0.2.0? You would need to update the plugin first using the Marketplace update feature within Cura.

**Comment by qkdefus** [comment]
Thank you, I will test this as soon as I get my printer up and running again 👍

**Comment by qkdefus** [comment]
seem to work fine on my end, tested on latest cura 4.13beta

**Comment by rgomezjnr** [comment]
Great thanks closing this issue.
