### ISSUE TITLE
[full_name_machine]?

### ISSUE THREAD

**Issue by DaniDiaz71** [rgomezjnr/GcodeFilenameFormatPlus#7]
Hi,

i would like know if is there any way to add something like [full_name_machine]? I'm trying to add full name machine to gcode file but i'm not able to do it :( 

Thanks!

**Comment by rgomezjnr** [comment]
Hello yes [printer_name] is what you're looking for.

**Comment by DaniDiaz71** [comment]
ok thank you, i didn't understand "printer manufacturer and model"
